"""Generate CICS file-control handlers: one COBOL program per VSAM cluster (FH<DATASET>).

CICS FILE() names from app/csd/CARDDEMO.CSD map onto the same indexed files the batch stream
uses; AIX paths (CARDAIX, CXACAIX) are the cluster's alternate key, so the online and batch
sides share one copy of the data exactly as they share the VSAM clusters on the mainframe.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from catalog import DATASETS  # noqa: E402

# CSD DEFINE FILE -> (cluster, path) ; path 'P' = primary key, 'A' = first alternate key
FCT = {"ACCTDAT": ("ACCTDATA", "P"), "CARDDAT": ("CARDDATA", "P"), "CARDAIX": ("CARDDATA", "A"),
       "CCXREF": ("CARDXREF", "P"), "CXACAIX": ("CARDXREF", "A"), "CUSTDAT": ("CUSTDATA", "P"),
       "TRANSACT": ("TRANSACT", "P"), "USRSEC": ("USRSEC", "P")}


def fh_source(ds) -> str:
    off, ln = ds.key
    alt = ds.alt_keys[0] if ds.alt_keys else None
    alt_sel = (f"\n           ALTERNATE RECORD KEY IS F-AK{' WITH DUPLICATES' if alt[2] else ''}"
               if alt else "")

    def keyrec(name, o, l):
        filler = f"\n           05 FILLER PIC X({o})." if o else ""
        return f"       01 F-R-{name}.{filler}\n           05 {name} PIC X({l})."
    alt_rec = keyrec("F-AK", alt[0], alt[1]) if alt else ""
    on_alt = lambda primary, alternate: (  # noqa: E731
        f"IF FH-PATH = 'A'\n                 {alternate}\n              ELSE\n                 {primary}\n"
        f"              END-IF" if alt else primary)
    return f"""       IDENTIFICATION DIVISION.
       PROGRAM-ID. FH{ds.name}.
      * Generated by legacy-runtime/cics/gen_fh.py - CICS file control
      * for cluster {ds.dsn}.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT F ASSIGN TO {ds.name}
           ORGANIZATION IS INDEXED ACCESS MODE IS DYNAMIC
           RECORD KEY IS F-PK{alt_sel}
           FILE STATUS IS WS-ST.
       DATA DIVISION.
       FILE SECTION.
       FD F RECORD CONTAINS {ds.lrecl} CHARACTERS.
       01 F-REC PIC X({ds.lrecl}).
{keyrec("F-PK", off, ln)}
{alt_rec}
       WORKING-STORAGE SECTION.
       01 WS-ST PIC XX.
       01 WS-OPEN PIC X VALUE 'N'.
       01 WS-STARTED PIC X VALUE 'N'.
       LINKAGE SECTION.
       01 FH-FUNC PIC X(8).
       01 FH-PATH PIC X.
       01 FH-KEY PIC X(32).
       01 FH-REC PIC X({ds.lrecl}).
       01 FH-STATUS PIC XX.
       PROCEDURE DIVISION USING FH-FUNC FH-PATH FH-KEY FH-REC FH-STATUS.
           IF FH-FUNC = 'CLOSE'
              IF WS-OPEN = 'Y' CLOSE F MOVE 'N' TO WS-OPEN END-IF
              MOVE '00' TO FH-STATUS
              GOBACK
           END-IF
           IF WS-OPEN = 'N'
              OPEN I-O F
              IF WS-ST NOT = '00' AND WS-ST NOT = '05'
                 MOVE WS-ST TO FH-STATUS GOBACK
              END-IF
              MOVE 'Y' TO WS-OPEN
           END-IF
           EVALUATE FH-FUNC
           WHEN 'READ'
              PERFORM SET-KEY
              {on_alt("READ F KEY IS F-PK", "READ F KEY IS F-AK")}
              PERFORM RETURN-REC
           WHEN 'READGE'
              PERFORM SET-KEY
              {on_alt("START F KEY >= F-PK", "START F KEY >= F-AK")}
              IF WS-ST = '00' READ F NEXT END-IF
              PERFORM RETURN-REC
           WHEN 'WRITE'
              MOVE FH-REC TO F-REC
              WRITE F-REC
           WHEN 'REWRITE'
              MOVE FH-REC TO F-REC
              REWRITE F-REC
           WHEN 'DELETE'
              PERFORM SET-KEY
              DELETE F
           WHEN 'STARTBR'
              PERFORM SET-KEY
              {on_alt("START F KEY >= F-PK", "START F KEY >= F-AK")}
              MOVE 'Y' TO WS-STARTED
           WHEN 'STARTEQ'
              PERFORM SET-KEY
              {on_alt("START F KEY = F-PK", "START F KEY = F-AK")}
              MOVE 'Y' TO WS-STARTED
           WHEN 'READNEXT'
              MOVE 'N' TO WS-STARTED
              READ F NEXT
              PERFORM RETURN-REC
           WHEN 'READPREV'
      * READPREV straight after STARTBR returns the record STARTBR
      * positioned on (CICS semantics), then walks backwards.
              IF WS-STARTED = 'Y'
                 MOVE 'N' TO WS-STARTED
                 PERFORM SET-KEY
                 {on_alt("READ F KEY IS F-PK", "READ F KEY IS F-AK")}
              ELSE
                 READ F PREVIOUS
              END-IF
              PERFORM RETURN-REC
           WHEN 'ENDBR'
              MOVE 'N' TO WS-STARTED
              MOVE '00' TO WS-ST
           WHEN OTHER
              MOVE '9F' TO WS-ST
           END-EVALUATE
           MOVE WS-ST TO FH-STATUS
           GOBACK.
       SET-KEY.
           {on_alt(f"MOVE FH-KEY({1}:{ln}) TO F-PK", f"MOVE FH-KEY(1:{alt[1] if alt else 1}) TO F-AK")}.
       RETURN-REC.
           IF WS-ST = '00' OR WS-ST = '02'
              MOVE F-REC TO FH-REC
              MOVE SPACES TO FH-KEY
              {on_alt(f"MOVE F-PK TO FH-KEY(1:{ln})", f"MOVE F-AK TO FH-KEY(1:{alt[1] if alt else 1})")}
           END-IF.
"""


if __name__ == "__main__":
    out = Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)
    for name in sorted({c for c, _ in FCT.values()}):
        (out / f"FH{name}.cbl").write_text(fh_source(DATASETS[name]))
    (out / "fct.txt").write_text("".join(f"{k} FH{c} {p}\n" for k, (c, p) in FCT.items()))
