"""Generate IDCAMS-REPRO equivalents (load PS -> KSDS, unload KSDS -> PS) per dataset."""
from catalog import DATASETS


def repro_source(ds) -> str:
    off, ln = ds.key
    alt_sel = "".join(
        f"\n           ALTERNATE RECORD KEY IS KS-ALT{i}{' WITH DUPLICATES' if dup else ''}"
        for i, (_, _, dup) in enumerate(ds.alt_keys, 1))
    def keyrec(name, o, l):
        filler = f"\n           05 FILLER PIC X({o})." if o else ""
        return f"       01 KS-R-{name}.{filler}\n           05 {name} PIC X({l})."
    alt_recs = "\n".join(keyrec(f"KS-ALT{i}", o, l) for i, (o, l, _) in enumerate(ds.alt_keys, 1))
    return f"""       IDENTIFICATION DIVISION.
       PROGRAM-ID. RP{ds.name}.
      * Generated by legacy-runtime/gen_repro.py - IDCAMS REPRO stand-in.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT PS-FILE ASSIGN TO PSFILE
           ORGANIZATION IS SEQUENTIAL FILE STATUS IS WS-PS-ST.
           SELECT KS-FILE ASSIGN TO KSFILE
           ORGANIZATION IS INDEXED ACCESS MODE IS DYNAMIC
           RECORD KEY IS KS-KEY{alt_sel}
           FILE STATUS IS WS-KS-ST.
       DATA DIVISION.
       FILE SECTION.
       FD PS-FILE RECORD CONTAINS {ds.lrecl} CHARACTERS.
       01 PS-REC PIC X({ds.lrecl}).
       FD KS-FILE RECORD CONTAINS {ds.lrecl} CHARACTERS.
       01 KS-REC PIC X({ds.lrecl}).
{keyrec("KS-KEY", off, ln)}
{alt_recs}
       WORKING-STORAGE SECTION.
       01 WS-PS-ST PIC XX.
       01 WS-KS-ST PIC XX.
       01 WS-MODE PIC X(6).
       01 WS-EOF PIC X VALUE 'N'.
       01 WS-COUNT PIC 9(9) VALUE 0.
       01 WS-DUPS PIC 9(9) VALUE 0.
       PROCEDURE DIVISION.
           ACCEPT WS-MODE FROM ENVIRONMENT 'REPRO_MODE'
           IF WS-MODE = 'UNLOAD'
              PERFORM UNLOAD-KS
           ELSE
              PERFORM LOAD-KS
           END-IF
           DISPLAY 'RP{ds.name} ' WS-MODE ' RECORDS=' WS-COUNT
                   ' DUPKEYS=' WS-DUPS
           IF WS-DUPS > 0 MOVE 8 TO RETURN-CODE END-IF
           STOP RUN.
       LOAD-KS.
           OPEN INPUT PS-FILE
           OPEN OUTPUT KS-FILE
           PERFORM UNTIL WS-EOF = 'Y'
              READ PS-FILE AT END MOVE 'Y' TO WS-EOF
              NOT AT END
                 MOVE PS-REC TO KS-REC
                 WRITE KS-REC
                    INVALID KEY ADD 1 TO WS-DUPS
                    NOT INVALID KEY ADD 1 TO WS-COUNT
                 END-WRITE
              END-READ
           END-PERFORM
           CLOSE PS-FILE KS-FILE.
       UNLOAD-KS.
           OPEN INPUT KS-FILE
           OPEN OUTPUT PS-FILE
           PERFORM UNTIL WS-EOF = 'Y'
              READ KS-FILE NEXT AT END MOVE 'Y' TO WS-EOF
              NOT AT END
                 WRITE PS-REC FROM KS-REC
                 ADD 1 TO WS-COUNT
              END-READ
           END-PERFORM
           CLOSE PS-FILE KS-FILE.
"""


if __name__ == "__main__":
    import sys
    from pathlib import Path
    out = Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)
    for ds in DATASETS.values():
        if ds.key:
            (out / f"RP{ds.name}.cbl").write_text(repro_source(ds))
